name: Generate and Deploy InteractiveHtmlBom with MkDocs

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker
      - name: Build Docker image
        run: |
          docker build -t kicad-ihbom-env .

      - name: Build MkDocs site
        run: |
          pip install mkdocs mkdocs-material
          mkdocs build

      - name: Launch fake X display
        run: |
          Xvfb :99 -screen 0 1024x768x16 &

      - name: Generate iBOMs
        run: |
          docker run --rm \
            -v "$(pwd):/workspace" \
            kicad-ihbom-env bash -c \
            "DISPLAY=:99 generate_interactive_bom MotionControl.kicad_pcb --no-browser --dest-dir site/ibom/ --name-format motioncontrol --dark-mode --layer-view F --show-fields Value,Footprint,Part --highlight-pin1 selected || true &&"
            "DISPLAY=:99 generate_interactive_bom OpticalSensor/OpticalSensor.kicad_pcb --no-browser --dest-dir site/ibom/ --name-format opticalendstop --dark-mode --layer-view F --show-fields Value,Footprint,Part --highlight-pin1 selected  || true &&"
            "DISPLAY=:99 generate_interactive_bom MagneticSensor/MagneticSensor.kicad_pcb --no-browser --dest-dir site/ibom/ --name-format magencoder --dark-mode --layer-view F --show-fields Value,Footprint,Part --highlight-pin1 selected  || true &&"

      - name: Debug ls
        run: |
          ls site

      # Prepare artifacts for GitHub Pages deployment
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: site

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1

